config/routes.rb
RelatedSortable::Application.routes.draw do
  resources :paragraphs

  resources :chapters

  resources :books do
    resources :chapters
  end

  resources :series do
    resources :stories do
      collection do
        post 'sort'
      end
    end
  end

  resources :stories do
    collection do
      post 'sort'
    end
  end
  root "stories#index"

  

end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :set_paragraph, only: [:show, :edit, :update, :destroy]

  # GET /paragraphs
  # GET /paragraphs.json
  def index
    @paragraphs = Paragraph.all
  end

  # GET /paragraphs/1
  # GET /paragraphs/1.json
  def show
  end

  # GET /paragraphs/new
  def new
    @paragraph = Paragraph.new
  end

  # GET /paragraphs/1/edit
  def edit
  end

  # POST /paragraphs
  # POST /paragraphs.json
  def create
    @paragraph = Paragraph.new(paragraph_params)

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully created.' }
        format.json { render action: 'show', status: :created, location: @paragraph }
      else
        format.html { render action: 'new' }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragraphs/1
  # PATCH/PUT /paragraphs/1.json
  def update
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1
  # DELETE /paragraphs/1.json
  def destroy
    @paragraph.destroy
    respond_to do |format|
      format.html { redirect_to paragraphs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paragraph_params
      params.require(:paragraph).permit(:content, :order)
    end
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/views/paragraphs/_form.html.erb
<%= form_for(@paragraph) do |f| %>
  <% if @paragraph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paragraph.errors.count, "error") %> prohibited this paragraph from being saved:</h2>

      <ul>
      <% @paragraph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paragraphs/edit.html.erb
<h1>Editing paragraph</h1>

<%= render 'form' %>

<%= link_to 'Show', @paragraph %> |
<%= link_to 'Back', paragraphs_path %>

app/views/paragraphs/index.html.erb
<h1>Listing paragraphs</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @paragraphs.each do |paragraph| %>
      <tr>
        <td><%= paragraph.content %></td>
        <td><%= paragraph.order %></td>
        <td><%= link_to 'Show', paragraph %></td>
        <td><%= link_to 'Edit', edit_paragraph_path(paragraph) %></td>
        <td><%= link_to 'Destroy', paragraph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paragraph', new_paragraph_path %>

app/views/paragraphs/new.html.erb
<h1>New paragraph</h1>

<%= render 'form' %>

<%= link_to 'Back', paragraphs_path %>

app/views/paragraphs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @paragraph.content %>
</p>

<p>
  <strong>Order:</strong>
  <%= @paragraph.order %>
</p>

<%= link_to 'Edit', edit_paragraph_path(@paragraph) %> |
<%= link_to 'Back', paragraphs_path %>