config/routes.rb
RelatedSortable::Application.routes.draw do
  resources :paragraphs

  resources :chapters

  resources :books do
    resources :chapters
  end

  resources :series do
    resources :stories do
      collection do
        post 'sort'
      end
    end
  end

  resources :stories do
    collection do
      post 'sort'
    end
  end
  root "stories#index"

  

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
    @series.stories.build
  end

  # GET /series/1/edit
  def edit
    @series.stories.build
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render action: 'show', status: :created, location: @series }
      else
        format.html { render action: 'new' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name, :stories, :stories_attributes => [
      :id, :series_id, :_destroy, :description, :position, :title])
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= simple_form_for @series do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, input_html: { class: "text_field"} %>
  <div id="stories-container" data-update-url="<%= sort_series_stories_url(@series) %>">
    <%= f.simple_fields_for :stories do |stories_form| %>
      <%= content_tag_for :div, stories_form.object, :class => "duplicatable_nested_form" do %>
          <%= stories_form.input :title, input_html: { class: "text_field"} %>
          <%= stories_form.input :description, input_html: { class: "text_field"} %>
          <% if stories_form.object.new_record? %>
            <%= link_to "Remove", "", :remote => true, :class => "destroy_duplicate_nested_form" %>
          <% else %>
            <%= link_to "Remove", series_story_path(@series, stories_form.object), :method => :delete, :remote => true, :class => "destroy_duplicate_nested_form" %>
            <%= stories_form.input :id, as: :hidden %>
          <% end %>
      <% end %>
    <% end %>
    <%= link_to "Add Another Story", "", :class => "duplicate_nested_form" %>
  </div>
  <br/>
  <%= f.button :submit %>
<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.name %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @series.name %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>